# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-15 15:13
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.CharField(max_length=60, unique=True)),
                ('allow_foreign_compare', models.IntegerField()),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_people_classify_classifies_parent', to='model_people.Classify')),
            ],
            options={
                'abstract': False,
                'db_table': 'model_people_classify',
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('data', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60, unique=True), size=None)),
                ('classify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_people_classify', to='model_people.Classify')),
            ],
            options={
                'abstract': False,
                'db_table': 'model_people_field',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('properties', django.contrib.postgres.fields.jsonb.JSONField()),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_people_model_gallery', to='media.Gallery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_people_model_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'db_table': 'model_people',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, unique=True)),
                ('content', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('first', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='model_people_review_first', to='model_people.Model')),
                ('second', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='model_people_review_second', to='model_people.Model')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_people_review_reviewer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'db_table': 'model_people_review',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='model_people.Model')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_people_vote_voter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'db_table': 'model_people_vote',
            },
        ),
    ]
