# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-19 11:56
from __future__ import unicode_literals

import app.media.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, unique=True)),
                ('description', models.TextField(null=True)),
                ('slug', models.CharField(max_length=160, unique=True)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='media.Gallery')),
            ],
            options={
                'ordering': ['id'],
                'db_table': 'media_gallery_relationship',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, unique=True)),
                ('description', models.TextField(null=True)),
                ('path', versatileimagefield.fields.VersatileImageField(upload_to=app.media.models.path_and_rename, verbose_name='Path')),
                ('path_ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='galleryrelationship',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Image'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='featured',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Image'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='galleryrelationship',
            unique_together=set([('gallery', 'image')]),
        ),
    ]
