# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-13 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_food', '0002_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classify',
            name='fields',
        ),
    ]
