# Generated by Django 2.0.3 on 2018-03-29 07:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compare',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_field', to='thing.Field'),
        ),
        migrations.AddField(
            model_name='thing',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
