# Generated by Django 2.0.3 on 2018-03-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thing', '0002_auto_20180329_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='is_edited',
            field=models.BooleanField(default=True),
        ),
    ]
