# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thing', '0004_thing_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='compare',
            name='classify',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compare_classify', to='thing.Classify'),
        ),
    ]
