# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thing', '0005_compare_classify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classify',
            name='description',
            field=models.CharField(blank=True, max_length=220),
        ),
    ]
