# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-08 11:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thing', '0006_auto_20180403_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now=True)),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thing_contributed', to='thing.Thing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_contributed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='classify',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
