# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-09 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thing', '0007_auto_20180408_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classify',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='classify',
            name='slug',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='slug',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='thing',
            name='slug',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
